using System.Globalization;
using EorzeaArsenal.Abstractions;

namespace EorzeaArsenal.Localization;

/// <summary>
/// Default <see cref="ILocalizer"/> with built-in German and English resources. Unknown keys
/// return the key itself so missing translations are obvious in the UI. Resources are embedded
/// dictionaries to avoid any external resource/IO dependency (R41).
/// </summary>
public sealed class Localizer : ILocalizer
{
    /// <summary>The English language code.</summary>
    public const string English = "en";

    /// <summary>The German language code.</summary>
    public const string German = "de";

    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        [LocKeys.PluginName] = "Eorzea Arsenal",
        [LocKeys.ConfigWindowTitle] = "Eorzea Arsenal — Settings",
        [LocKeys.CommandHelp] = "Push your gearsets to Eorzea Arsenal (opens settings if not yet enabled).",
        [LocKeys.Language] = "Language",
        [LocKeys.Save] = "Save",
        [LocKeys.Close] = "Close",

        [LocKeys.TosHeader] = "Third-party tool notice",
        [LocKeys.TosBody] =
            "Dalamud and third-party tools violate the FFXIV Terms of Service. Using this plugin " +
            "is at your own risk. Connecting and pushing your gear is strictly opt-in.",
        [LocKeys.TosAccept] = "I understand and accept the risk",

        [LocKeys.StatusConnected] = "Connected",
        [LocKeys.StatusDisconnected] = "Not connected",

        [LocKeys.BaseUrlLabel] = "API base URL",
        [LocKeys.BaseUrlHint] = "Full URL including /api/v1, e.g. http://127.0.0.1:8080/api/v1",
        [LocKeys.TestConnection] = "Test connection",
        [LocKeys.TestOk] = "Connection OK (protocol v{0}).",
        [LocKeys.TestFailed] = "Connection failed: {0}",

        [LocKeys.ConnectHeader] = "Connect",
        [LocKeys.ConnectDeviceFlow] = "Connect via browser",
        [LocKeys.ConnectOpenBrowser] = "Open this page in your browser and approve the code:",
        [LocKeys.ConnectUserCode] = "Your code: {0}",
        [LocKeys.ConnectWaiting] = "Waiting for approval…",
        [LocKeys.ConnectSuccess] = "Connected successfully.",
        [LocKeys.ConnectFailed] = "Connection failed: {0}",
        [LocKeys.ConnectCancel] = "Cancel",
        [LocKeys.ConnectOpenBrowserAgain] = "Open browser again",
        [LocKeys.PasteKeyLabel] = "API key",
        [LocKeys.PasteKeyHint] = "Or paste a key created at /me/keys in the web app.",
        [LocKeys.PasteKeyButton] = "Use pasted key",
        [LocKeys.Disconnect] = "Disconnect",

        [LocKeys.AutoPush] = "Push automatically",
        [LocKeys.AutoPushHint] = "Push at most every {0} minutes when something changed.",
        [LocKeys.PushOnLogin] = "Push on login",
        [LocKeys.EnablePushMaster] = "Enable connecting and pushing",
        [LocKeys.EnablePushMasterHint] = "Master opt-in. While off, the plugin never contacts the API.",

        [LocKeys.PushStarted] = "Pushing gear…",
        [LocKeys.PushSuccess] = "Pushed {0} gearset(s).",
        [LocKeys.PushNotConnected] = "Not connected. Connect first.",
        [LocKeys.PushNotLoggedIn] = "No character is logged in.",
        [LocKeys.PushInProgress] = "A push is already in progress.",
        [LocKeys.PushInvalid] = "Gear data failed validation; nothing was sent.",
        [LocKeys.PushNothing] = "No gearsets to push.",

        [LocKeys.Error401] = "Your key is invalid or expired. Please reconnect.",
        [LocKeys.Error403] = "Your key lacks the gear:write permission. Reconnect with a correct key.",
        [LocKeys.Error409] = "This character is already linked to another account.",
        [LocKeys.Error422] = "The server rejected the gear data (validation).",
        [LocKeys.Error400] = "The payload was too large or malformed.",
        [LocKeys.Error429] = "Rate limit reached (30 uploads/hour). Backing off.",
        [LocKeys.ErrorNetwork] = "Could not reach the server. Check the base URL and your connection.",
        [LocKeys.ErrorUnexpected] = "Unexpected error.",

        [LocKeys.StatusWindowTitle] = "Eorzea Arsenal — Status",
        [LocKeys.StatusLastPush] = "Last push",
        [LocKeys.StatusNever] = "never",
        [LocKeys.StatusLastResult] = "Last result",
        [LocKeys.StatusRateLimited] = "Rate limited — backing off for ~{0}s.",
        [LocKeys.PushNow] = "Push now",
        [LocKeys.OpenSettings] = "Open settings",
        [LocKeys.OpenStatus] = "Open status",
        [LocKeys.OpenWebApp] = "Open web app",
        [LocKeys.PreviewButton] = "Preview what will be sent",
        [LocKeys.PreviewHeader] = "{0} gearset(s) would be sent:",
        [LocKeys.PreviewEmpty] = "Nothing to send (not logged in or no valid gearsets).",
        [LocKeys.ScopeMissing] = "Connected, but the key is missing the gear:write permission.",
        [LocKeys.PushOnChange] = "Push when a gearset changes",
        [LocKeys.PushOnChangeHint] = "Detects in-game changes and pushes (still rate-limited).",
        [LocKeys.UseToasts] = "Show toast notifications",
        [LocKeys.Verbosity] = "Log detail",
        [LocKeys.WebAppUrlLabel] = "Web app URL (optional)",
        [LocKeys.WebAppUrlHint] = "Used by the \"Open web app\" button. If empty, derived from the base URL.",
        [LocKeys.CharactersHeader] = "Characters",
        [LocKeys.CharactersHint] = "Choose which of your characters may be pushed.",
        [LocKeys.CharactersNone] = "No characters seen yet — log in to add one.",
        [LocKeys.CharacterDisabled] = "This character is disabled for pushing.",

        [LocKeys.BisWindowTitle] = "Eorzea Arsenal — Gear vs BiS",
        [LocKeys.BisRefresh] = "Compare with BiS",
        [LocKeys.BisOpen] = "Gear vs BiS",
        [LocKeys.BisLoading] = "Loading BiS targets…",
        [LocKeys.BisReconnect] = "Your key has no read access. Please reconnect to enable BiS comparison.",
        [LocKeys.BisNone] = "No BiS target found. Pin one for your gearsets in the web app.",
        [LocKeys.BisComplete] = "complete",
        [LocKeys.BisSummary] = "{0}/{1} slots match",
        [LocKeys.BisHave] = "have {0} → BiS {1}",
        [LocKeys.BisMissing] = "empty → BiS {0}",
        [LocKeys.BisMateriaDiff] = "materia differs",
        [LocKeys.BisTooltipHeader] = "Eorzea Arsenal — BiS",
        [LocKeys.BisTooltipToggle] = "Show BiS info on item hover",
        [LocKeys.BisShowSourcing] = "Show 'how to get it' on BiS pieces",
        [LocKeys.BisShowSourcingHint] = "On a BiS piece's hover, add where it comes from and what it costs (savage / tome). Reads impersonal game data from the server.",
        [LocKeys.BisYouHave] = "equipped: {0}",
        [LocKeys.BisOwned] = "you own this item",
        [LocKeys.BisNotOwned] = "not in your inventory/armoury",
        [LocKeys.BisMateriaList] = "Materia: {0}",
        [LocKeys.BisMateriaWrong] = "Wrong: {0}",
        [LocKeys.BisMateriaMissing] = "Missing: {0}",
        [LocKeys.BisNoTarget] = "No BiS target for this gearset (#{0}). Pin one in the web app.",
        [LocKeys.BisScopeCurrent] = "Current set",
        [LocKeys.BisScopeAll] = "All sets",
        [LocKeys.BisFilterLabel] = "Filter",
        [LocKeys.BisFilterAll] = "All slots",
        [LocKeys.BisFilterIncomplete] = "Incomplete only",
        [LocKeys.BisFilterMateria] = "Materia issues only",
        [LocKeys.BisNothingShown] = "Nothing to show with the current filter.",
        [LocKeys.BisCopyName] = "Copy name",
        [LocKeys.BisItemHint] = "Left-click: link in chat · Right-click: more options",
        [LocKeys.DtrClickHint] = "Click: open status",
        [LocKeys.ShowDtrBar] = "Server info bar entry",
        [LocKeys.ShowDtrBarHint] = "Show a compact status entry (last push) in the in-game server info bar (top-right).",
        [LocKeys.BisShoppingList] = "Shopping list",
        [LocKeys.BisShoppingItems] = "Items to get",
        [LocKeys.BisShoppingMateria] = "Materia to get",
        [LocKeys.BisShoppingEmpty] = "Nothing to get — you own everything for the shown sets!",
        [LocKeys.BisGridView] = "Grid",

        [LocKeys.SyncInventory] = "Also upload owned items",
        [LocKeys.SyncInventoryHint] =
            "Uploads which gear you own (equipped, armoury, bags, saddlebag, glamour dresser) so the " +
            "web app can tick off what you already have. Opt-in, same as gear.",
        [LocKeys.SyncRetainers] = "Include retainers",
        [LocKeys.SyncRetainersHint] = "Also scan a retainer's gear when you open it at a summoning bell.",
        [LocKeys.InventorySyncButton] = "Sync inventory",
        [LocKeys.InventorySyncHint] = "Visit your retainers to refresh their stock.",
        [LocKeys.InventoryStarted] = "Syncing inventory…",
        [LocKeys.InventorySuccess] = "Synced {0} item(s) across {1} scope(s).",
        [LocKeys.StatusLastInventory] = "Last inventory sync",
        [LocKeys.Error403Inventory] = "Your key lacks the inventory:write permission. Reconnect to enable inventory upload.",

        [LocKeys.SyncWeekly] = "Also sync the weekly checklist",
        [LocKeys.SyncWeeklyHint] =
            "Fills your weekly checklist in the web app automatically from the game (tomestones this " +
            "week, Custom Deliveries done). Only values it can read with certainty are sent, so your " +
            "manual entries are never overwritten. Opt-in, same as gear.",
        [LocKeys.WeeklySyncButton] = "Sync weekly",
        [LocKeys.WeeklyStarted] = "Syncing weekly checklist…",
        [LocKeys.WeeklySuccess] = "Synced {0} weekly field(s).",
        [LocKeys.StatusLastWeekly] = "Last weekly sync",
        [LocKeys.Error403Weekly] = "Your key lacks the characters:write permission. Reconnect to enable the weekly checklist.",

        [LocKeys.SectionActions] = "Actions",
        [LocKeys.SectionView] = "View",
        [LocKeys.SectionManage] = "Manage",
        [LocKeys.StatusConnectHint] = "Not connected. Open the settings to link your Eorzea Arsenal account.",
        [LocKeys.TabSync] = "Sync",
        [LocKeys.TabDisplay] = "Display",
        [LocKeys.TabCharacters] = "Characters",
        [LocKeys.TabConnection] = "Connection",

        [LocKeys.LogWindowTitle] = "Eorzea Arsenal — Log",
        [LocKeys.OpenLog] = "Log",
        [LocKeys.LogCopy] = "Copy",
        [LocKeys.LogClear] = "Clear",
        [LocKeys.LogEmpty] = "No messages yet.",

        ["slot.weapon"] = "Weapon",
        ["slot.offhand"] = "Off Hand",
        ["slot.head"] = "Head",
        ["slot.body"] = "Body",
        ["slot.hands"] = "Hands",
        ["slot.legs"] = "Legs",
        ["slot.feet"] = "Feet",
        ["slot.ears"] = "Ears",
        ["slot.neck"] = "Neck",
        ["slot.wrists"] = "Wrists",
        ["slot.ringleft"] = "Ring (left)",
        ["slot.ringright"] = "Ring (right)",

        ["source.crafted"] = "Crafted",
        ["source.raid"] = "Raid",
        ["source.tome"] = "Tomestone",
        ["source.augmented_tome"] = "Tome+",
        ["source.alliance"] = "Alliance Raid",
        ["source.dungeon"] = "Dungeon",
        ["source.extreme"] = "Extreme",
        ["source.trial"] = "Trial",
        ["source.ultimate"] = "Ultimate",
        ["source.relic"] = "Relic",
        ["source.pvp"] = "PvP",
        ["source.other"] = "Other",

        [LocKeys.TeamsOpen] = "Teams",
        [LocKeys.SyncTeams] = "Teams companion",
        [LocKeys.SyncTeamsHint] = "Show your teams' calendar, mit cheat sheets, content hub, farm and FFLogs in-game, RSVP and report absences, and get toasts for loot, reminders and new events. Needs a key with teams:read / teams:write.",
        [LocKeys.TeamsDisabledHint] = "The Teams companion is off. Enable it in the settings (needs a key with the teams scopes).",
        [LocKeys.TeamsScopeHint] = "Your key is missing a teams scope — reconnect once in the settings.",
        [LocKeys.TeamsTabCalendar] = "Calendar",
        [LocKeys.TeamsTabMit] = "Mit sheet",
        [LocKeys.TeamsTabContent] = "Content",
        [LocKeys.TeamsTabFarm] = "Farm",
        [LocKeys.TeamsTabLogs] = "FFLogs",
        [LocKeys.TeamsTabAbsence] = "Absence",
        [LocKeys.TeamsTeamLabel] = "Team",
        [LocKeys.TeamsLoading] = "Loading…",
        [LocKeys.TeamsNoTeams] = "No teams.",
        [LocKeys.TeamsRefresh] = "Refresh",
        [LocKeys.TeamsHelp] = "Help",
        [LocKeys.TeamsWorking] = "Working…",
        [LocKeys.TeamsSaved] = "Saved.",
        [LocKeys.TeamsNoEvents] = "No upcoming events.",
        [LocKeys.TeamsContentsLabel] = "Content",
        [LocKeys.TeamsAttendCounts] = "Yes {0} · Maybe {1} · No {2} · of {3}",
        [LocKeys.TeamsRsvpYes] = "Yes",
        [LocKeys.TeamsRsvpMaybe] = "Maybe",
        [LocKeys.TeamsRsvpNo] = "No",
        [LocKeys.TeamsPlanLabel] = "Plan",
        [LocKeys.TeamsJobLabel] = "Job",
        [LocKeys.TeamsAllJobs] = "All jobs",
        [LocKeys.TeamsNoPlan] = "No mit plan.",
        [LocKeys.TeamsMechanics] = "Mechanics",
        [LocKeys.TeamsCooldowns] = "Cooldowns",
        [LocKeys.TeamsNoPlacements] = "No cooldowns for this job.",
        [LocKeys.TeamsBosses] = "Bosses & drops",
        [LocKeys.TeamsResources] = "Resources",
        [LocKeys.TeamsNoContent] = "No content.",
        [LocKeys.TeamsNoFarm] = "No shared gearsets.",
        [LocKeys.TeamsCore] = "Core",
        [LocKeys.TeamsSubstitute] = "Sub",
        [LocKeys.TeamsTargetNone] = "No BiS target.",
        [LocKeys.TeamsComplete] = "BiS complete.",
        [LocKeys.TeamsMissing] = "Still missing",
        [LocKeys.TeamsLogsNotConnected] = "FFLogs is not connected for this team.",
        [LocKeys.TeamsNoReports] = "No recent reports.",
        [LocKeys.TeamsKillsWipes] = "{0} kills · {1} wipes",
        [LocKeys.TeamsAbsenceFrom] = "From",
        [LocKeys.TeamsAbsenceTo] = "To",
        [LocKeys.TeamsAbsenceNote] = "Note",
        [LocKeys.TeamsAbsenceAdd] = "Add absence",
        [LocKeys.TeamsAbsenceDelete] = "Delete",
        [LocKeys.TeamsAbsenceInvalid] = "Please enter valid dates.",
        [LocKeys.TeamsNoAbsences] = "No absences.",
        [LocKeys.TeamsErrorGeneric] = "Could not load. Try again.",
        [LocKeys.TeamsErrorForbidden] = "You are not allowed to do that.",
        [LocKeys.TeamsNotMember] = "You are not a member of this team.",
        [LocKeys.TeamsErrorNetwork] = "Network error. Retrying later.",
        [LocKeys.TeamsCalendarOpen] = "Calendar",
        [LocKeys.TeamsCalendarOpenWeb] = "Open in web",
        [LocKeys.TeamsCalendarPickDay] = "Pick a day to see its events.",
        [LocKeys.TeamsOpenWeb] = "Open in web",
        [LocKeys.TeamsPhasesLabel] = "Phases:",
        [LocKeys.TeamsFilterLabel] = "Mechanics:",
        [LocKeys.TeamsTagRaidwide] = "Raidwide",
        [LocKeys.TeamsTagTankbuster] = "Tankbuster",
        [LocKeys.TeamsTagOther] = "Other",
        [LocKeys.TeamsColTime] = "Time",
        [LocKeys.TeamsColMechanic] = "Mechanic",
        [LocKeys.TeamsRecast] = "Recast",
        [LocKeys.TeamsDuration] = "Duration",
        [LocKeys.TeamsResLink] = "Link",
        [LocKeys.TeamsResVideo] = "Video",
        [LocKeys.TeamsResPlan] = "Plan",
        [LocKeys.TeamsResNote] = "Note",
        [LocKeys.TeamsResImage] = "Image",
        [LocKeys.TeamsResPdf] = "PDF",
        [LocKeys.TeamsResFile] = "File",
        [LocKeys.TeamsFflogsReport] = "Report",
        [LocKeys.TabTeams] = "Teams",
        [LocKeys.TeamsDispIconText] = "Icon + text",
        [LocKeys.TeamsDispIcon] = "Icon only",
        [LocKeys.TeamsDispText] = "Text only",
        [LocKeys.TeamsMitDisplayLabel] = "Mit cooldowns",
        [LocKeys.TeamsMitDisplayHint] = "How cooldowns show in the mit timeline. Icon-only shows the name on hover.",
        [LocKeys.TeamsResourceDisplayLabel] = "Resource labels",
        [LocKeys.TeamsResourceDisplayHint] = "How a content resource's type (link/note/file…) is labelled.",
        [LocKeys.TeamsShowNotes] = "Show note text",
        [LocKeys.TeamsShowNotesHint] = "Show the full text of note resources inline (off shows only the title).",
        [LocKeys.TeamsRange] = "Range",
        [LocKeys.TeamsRadius] = "Radius",
        [LocKeys.TeamsCast] = "Cast",
        [LocKeys.TeamsInstant] = "Instant",
        [LocKeys.TeamsCalAllPresent] = "all present",
        [LocKeys.TeamsCalUnclear] = "unclear",
        [LocKeys.TeamsCalMissing] = "someone missing",
        [LocKeys.TeamsRecurring] = "recurring",
        [LocKeys.TeamsSingle] = "one-off",
        [LocKeys.TeamsTabEvents] = "Events",
        [LocKeys.TeamsShowPast] = "Show past ({0})",
        [LocKeys.TeamsDefaultJobLabel] = "Default job view",
        [LocKeys.TeamsDefaultCurrentJob] = "Current job",
        [LocKeys.TeamsDefaultAllJobsOpt] = "All jobs",
        [LocKeys.TeamsDefaultShowOther] = "Show 'other' mechanics by default",
        [LocKeys.TeamsDefaultShowOtherHint] = "When on, the mit timeline shows untagged/other mechanics too; off keeps it to raidwides and tankbusters.",
        [LocKeys.TeamsDefaultPhasesLabel] = "Default phases",
        [LocKeys.TeamsDefaultPhasesAll] = "All phases",
        [LocKeys.TeamsDefaultPhasesFirst] = "First phase only",
        [LocKeys.TeamsDefaultPhasesHint] = "Which phases are ticked when a mit plan is opened. You can still toggle them per plan.",
        [LocKeys.TeamsEventScale] = "Event text size",
        [LocKeys.TeamsEventScaleHint] = "Scales the text in the Events tab so long lists stay readable.",
        [LocKeys.TeamsFarmColSlot] = "Slot",
        [LocKeys.TeamsFarmColSource] = "Source",
        [LocKeys.TeamsFarmColHow] = "How to get it",
        [LocKeys.TeamsFarmUnknownSource] = "unknown",
        [LocKeys.TeamsFarmRetired] = "no longer obtainable",
        [LocKeys.TeamsFarmMarket] = "Market Board",
        [LocKeys.TeamsFarmCraft] = "Craft",
        [LocKeys.TeamsFarmCoffer] = "Coffer",
        [LocKeys.TeamsFarmWaysHeading] = "Ways to get it",
        [LocKeys.TeamsFarmHandIn] = "hand in",
        [LocKeys.TeamsFarmShowOnMap] = "Show NPC on map",
        [LocKeys.SourceStepFight] = "Fight",
        [LocKeys.SourceStepBuy] = "Buy",
        [LocKeys.SourceStepAugment] = "Upgrade",
        [LocKeys.SourceStepCraft] = "Craft",
        [LocKeys.SourceStepBase] = "Get the base piece",
        [LocKeys.SourceNoInfo] = "No sourcing info yet",
        [LocKeys.SourceHave] = "you have enough",
        [LocKeys.SourceBaseOwned] = "Base owned",
        [LocKeys.SourceOr] = "or",
        [LocKeys.WhatsNewOpen] = "What's new",
        [LocKeys.WhatsNewIntro] = "The important changes of each version, in short. The full technical changelog is on GitHub.",
        [LocKeys.WhatsNewInstalled] = "installed",
        [LocKeys.WhatsNewKindAdded] = "New",
        [LocKeys.WhatsNewKindImproved] = "Improved",
        [LocKeys.WhatsNewKindFixed] = "Fixed",
        [LocKeys.WhatsNewFullChangelog] = "Full changelog",
        [LocKeys.WhatsNewOnUpdate] = "Show 'what's new' after an update",
        [LocKeys.WhatsNewOnUpdateHint] = "Opens this list once after the plugin updated. Off: the menu entry is highlighted instead.",
        [LocKeys.TeamsAbsenceNew] = "New absence",
        [LocKeys.TeamsAbsenceEditing] = "Editing absence",
        [LocKeys.TeamsAbsenceUpdate] = "Save changes",
        [LocKeys.TeamsAbsenceCancel] = "Cancel",
        [LocKeys.TeamsAbsenceCurrent] = "Your absences",
        [LocKeys.TeamsAbsenceEdit] = "Edit",
        [LocKeys.TeamsAbsenceRangeInvalid] = "The end date is before the start date.",

        [LocKeys.AdvisorOpen] = "Purchase advisor",
        [LocKeys.AdvisorWindowTitle] = "Eorzea Arsenal — Purchase advisor",
        [LocKeys.AdvisorIntro] = "The gear on the way to BiS: what to buy next, and what you already have in stock for it.",
        [LocKeys.AdvisorSetLabel] = "Set",
        [LocKeys.AdvisorPlanHeading] = "Your saved plan",
        [LocKeys.AdvisorNoTarget] = "This set has no web identity yet, so no plan can be looked up for it. It appears as soon as the server sends the set's target with the BiS data.",
        [LocKeys.AdvisorNoPlan] = "No own layout saved for this set — the recommendation applies. Pick your pieces here, or build it in the web advisor.",
        [LocKeys.AdvisorNoCharacter] = "This character is not linked on the server yet. Push your gear once, then the advisor can be read.",
        [LocKeys.AdvisorPlanSaved] = "saved: {0}",
        [LocKeys.AdvisorPlanWorn] = "worn",
        [LocKeys.AdvisorPlanOwned] = "owned",
        [LocKeys.AdvisorPlanMissing] = "still missing",
        [LocKeys.AdvisorPlanSummary] = "{0}/{1} pieces done",
        [LocKeys.AdvisorViewRecommendation] = "Recommendation",
        [LocKeys.AdvisorViewPlan] = "My layout",
        [LocKeys.AdvisorSortLabel] = "Order",
        [LocKeys.AdvisorSortPower] = "Biggest gain",
        [LocKeys.AdvisorSortValue] = "Best value",
        [LocKeys.AdvisorSortCheap] = "Cheapest first",
        [LocKeys.AdvisorRefresh] = "Recalculate",
        [LocKeys.AdvisorBalance] = "{0} tomestones · weekly cap {1}",
        [LocKeys.AdvisorStepBuy] = "Buy",
        [LocKeys.AdvisorStepAugment] = "Upgrade",
        [LocKeys.AdvisorStepTrial] = "Farm (Extreme)",
        [LocKeys.AdvisorStepBooks] = "Trade books",
        [LocKeys.AdvisorStepEquip] = "Put it on",
        [LocKeys.AdvisorWhenNow] = "now",
        [LocKeys.AdvisorWhenWeeks] = "in {0} week(s)",
        [LocKeys.AdvisorWhenBooks] = "{0} book(s) short",
        [LocKeys.AdvisorCostTomes] = "{0} tomestones",
        [LocKeys.AdvisorVendor] = "at {0}",
        [LocKeys.AdvisorLeadsTo] = "towards {0}",
        [LocKeys.AdvisorNothingToDo] = "Nothing left to do — this set is done.",
        [LocKeys.AdvisorNoSteps] = "No step to plan: the {0} open slot(s) cannot be bought (Ultimate, relic, crafted) — they come down to the drop.",
        [LocKeys.AdvisorNeeds] = "Still needed",
        [LocKeys.AdvisorSave] = "Save layout",
        [LocKeys.AdvisorAdopt] = "Take the recommendation",
        [LocKeys.AdvisorDeletePlan] = "Delete layout",
        [LocKeys.AdvisorSaved] = "Saved.",
        [LocKeys.AdvisorSaveFailed] = "Could not save — your key may lack the plans permission.",
        [LocKeys.AdvisorIsRecommended] = "recommended",
        [LocKeys.AdvisorIsBis] = "BiS",
        [LocKeys.AdvisorLoadingOptions] = "Calculating…",
        [LocKeys.AdvisorUnsaved] = "unsaved changes",
        [LocKeys.TeamsNeedsRequires] = "the set needs",
        [LocKeys.TeamsStockUnknown] = "their stock is not visible to the plugin",
        [LocKeys.BisNeedsHeading] = "Still needed for this set",
        [LocKeys.BisNeedsTomes] = "Tomestones: {0} · you have {1}",
        [LocKeys.BisNeedsShort] = "{0} short",
        [LocKeys.BisNeedsWeeks] = "≈ {0} week(s)",
        [LocKeys.BisNeedsCovered] = "covered",
        [LocKeys.BisNeedsNothing] = "Nothing left to get for this set.",
        [LocKeys.BisNeedsUnknown] = "{0} slot(s) still open, but nothing is known about their cost: they cannot be bought (Ultimate, relic, crafted) or no purchase is recorded for them yet.",
        [LocKeys.AdvisorScale] = "Purchase advisor text size",
        [LocKeys.AdvisorScaleHint] = "Scales the advisor window. Item names are long and the pickers hold dozens of entries, so it starts a little larger.",
        [LocKeys.AdvisorNextBest] = "Best right now",
        [LocKeys.AdvisorProgress] = "progress",
        [LocKeys.AdvisorOnBis] = "On BiS",
        [LocKeys.AdvisorAvgIlvl] = "avg iLvl",
        [LocKeys.AdvisorYourSet] = "Your set",
        [LocKeys.AdvisorOrderHeading] = "Order — what first",
        [LocKeys.AdvisorLegend] = "Green = on BiS · Blue = you own it · Orange = next purchase · Grey = already best possible",
        [LocKeys.AdvisorSlotCapped] = "already best possible",
        [LocKeys.HoldingWhere] = "Where it sits",
        [LocKeys.HoldingBags] = "Inventory",
        [LocKeys.HoldingSaddlebag] = "Saddlebag",
        [LocKeys.HoldingArmoury] = "Armoury Chest",
        [LocKeys.HoldingEquipped] = "Equipped",
        [LocKeys.HoldingGlamour] = "Glamour Dresser",
        [LocKeys.HoldingArmoire] = "Armoire",
        [LocKeys.HoldingRetainer] = "Retainer",
        [LocKeys.HoldingManual] = "Marked on the website",
        [LocKeys.AdvisorStockHeading] = "Your stock",
        [LocKeys.AdvisorStockHint] = "Counted server-side, so retainers are included — as of their last visit.",
        [LocKeys.AdvisorStockEmpty] = "No stock list from the server yet.",
        [LocKeys.AdvisorStockMaterial] = "Upgrade materials",
        [LocKeys.AdvisorStockStone] = "Upgrade stone",
        [LocKeys.AdvisorStockBook] = "Books & tokens",
        [LocKeys.AdvisorLoading] = "Loading plan…",
        [LocKeys.AdvisorScopeHint] = "Your key has no access to plans — reconnect once in the settings.",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        [LocKeys.PluginName] = "Eorzea Arsenal",
        [LocKeys.ConfigWindowTitle] = "Eorzea Arsenal — Einstellungen",
        [LocKeys.CommandHelp] = "Überträgt deine Gearsets an Eorzea Arsenal (öffnet die Einstellungen, falls noch nicht aktiviert).",
        [LocKeys.Language] = "Sprache",
        [LocKeys.Save] = "Speichern",
        [LocKeys.Close] = "Schließen",

        [LocKeys.TosHeader] = "Hinweis zu Drittanbieter-Tools",
        [LocKeys.TosBody] =
            "Dalamud und Drittanbieter-Tools verstoßen gegen die FFXIV-Nutzungsbedingungen. Die Nutzung " +
            "dieses Plugins erfolgt auf eigenes Risiko. Das Verbinden und Übertragen deiner Ausrüstung ist " +
            "ausdrücklich freiwillig (Opt-in).",
        [LocKeys.TosAccept] = "Ich verstehe das Risiko und akzeptiere es",

        [LocKeys.StatusConnected] = "Verbunden",
        [LocKeys.StatusDisconnected] = "Nicht verbunden",

        [LocKeys.BaseUrlLabel] = "API-Basis-URL",
        [LocKeys.BaseUrlHint] = "Vollständige URL inkl. /api/v1, z. B. http://127.0.0.1:8080/api/v1",
        [LocKeys.TestConnection] = "Verbindung testen",
        [LocKeys.TestOk] = "Verbindung OK (Protokoll v{0}).",
        [LocKeys.TestFailed] = "Verbindung fehlgeschlagen: {0}",

        [LocKeys.ConnectHeader] = "Verbinden",
        [LocKeys.ConnectDeviceFlow] = "Über Browser verbinden",
        [LocKeys.ConnectOpenBrowser] = "Öffne diese Seite im Browser und bestätige den Code:",
        [LocKeys.ConnectUserCode] = "Dein Code: {0}",
        [LocKeys.ConnectWaiting] = "Warte auf Bestätigung…",
        [LocKeys.ConnectSuccess] = "Erfolgreich verbunden.",
        [LocKeys.ConnectFailed] = "Verbindung fehlgeschlagen: {0}",
        [LocKeys.ConnectCancel] = "Abbrechen",
        [LocKeys.ConnectOpenBrowserAgain] = "Browser erneut öffnen",
        [LocKeys.PasteKeyLabel] = "API-Schlüssel",
        [LocKeys.PasteKeyHint] = "Oder füge einen unter /me/keys erstellten Schlüssel ein.",
        [LocKeys.PasteKeyButton] = "Eingefügten Schlüssel verwenden",
        [LocKeys.Disconnect] = "Trennen",

        [LocKeys.AutoPush] = "Automatisch übertragen",
        [LocKeys.AutoPushHint] = "Höchstens alle {0} Minuten übertragen, wenn sich etwas geändert hat.",
        [LocKeys.PushOnLogin] = "Beim Login übertragen",
        [LocKeys.EnablePushMaster] = "Verbinden und Übertragen aktivieren",
        [LocKeys.EnablePushMasterHint] = "Haupt-Opt-in. Solange deaktiviert, kontaktiert das Plugin die API nie.",

        [LocKeys.PushStarted] = "Übertrage Ausrüstung…",
        [LocKeys.PushSuccess] = "{0} Gearset(s) übertragen.",
        [LocKeys.PushNotConnected] = "Nicht verbunden. Bitte zuerst verbinden.",
        [LocKeys.PushNotLoggedIn] = "Kein Charakter eingeloggt.",
        [LocKeys.PushInProgress] = "Eine Übertragung läuft bereits.",
        [LocKeys.PushInvalid] = "Ausrüstungsdaten ungültig; es wurde nichts gesendet.",
        [LocKeys.PushNothing] = "Keine Gearsets zum Übertragen.",

        [LocKeys.Error401] = "Dein Schlüssel ist ungültig oder abgelaufen. Bitte neu verbinden.",
        [LocKeys.Error403] = "Deinem Schlüssel fehlt die Berechtigung gear:write. Bitte mit korrektem Schlüssel verbinden.",
        [LocKeys.Error409] = "Dieser Charakter ist bereits mit einem anderen Konto verknüpft.",
        [LocKeys.Error422] = "Der Server hat die Ausrüstungsdaten abgelehnt (Validierung).",
        [LocKeys.Error400] = "Die Nutzlast war zu groß oder fehlerhaft.",
        [LocKeys.Error429] = "Ratenlimit erreicht (30 Uploads/Stunde). Warte ab.",
        [LocKeys.ErrorNetwork] = "Server nicht erreichbar. Prüfe die Basis-URL und deine Verbindung.",
        [LocKeys.ErrorUnexpected] = "Unerwarteter Fehler.",

        [LocKeys.StatusWindowTitle] = "Eorzea Arsenal — Status",
        [LocKeys.StatusLastPush] = "Letzte Übertragung",
        [LocKeys.StatusNever] = "nie",
        [LocKeys.StatusLastResult] = "Letztes Ergebnis",
        [LocKeys.StatusRateLimited] = "Ratenlimit — warte noch ~{0}s.",
        [LocKeys.PushNow] = "Jetzt übertragen",
        [LocKeys.OpenSettings] = "Einstellungen öffnen",
        [LocKeys.OpenStatus] = "Status öffnen",
        [LocKeys.OpenWebApp] = "Webapp öffnen",
        [LocKeys.PreviewButton] = "Vorschau: was wird gesendet",
        [LocKeys.PreviewHeader] = "{0} Gearset(s) würden gesendet:",
        [LocKeys.PreviewEmpty] = "Nichts zu senden (nicht eingeloggt oder keine gültigen Gearsets).",
        [LocKeys.ScopeMissing] = "Verbunden, aber dem Schlüssel fehlt die Berechtigung gear:write.",
        [LocKeys.PushOnChange] = "Bei Gearset-Änderung übertragen",
        [LocKeys.PushOnChangeHint] = "Erkennt Änderungen im Spiel und überträgt (weiterhin ratenbegrenzt).",
        [LocKeys.UseToasts] = "Toast-Benachrichtigungen anzeigen",
        [LocKeys.Verbosity] = "Log-Detailgrad",
        [LocKeys.WebAppUrlLabel] = "Webapp-URL (optional)",
        [LocKeys.WebAppUrlHint] = "Für den \"Webapp öffnen\"-Button. Leer = aus der Basis-URL abgeleitet.",
        [LocKeys.CharactersHeader] = "Charaktere",
        [LocKeys.CharactersHint] = "Wähle, welche deiner Charaktere übertragen werden dürfen.",
        [LocKeys.CharactersNone] = "Noch keine Charaktere erfasst — logge dich ein.",
        [LocKeys.CharacterDisabled] = "Dieser Charakter ist für die Übertragung deaktiviert.",

        [LocKeys.BisWindowTitle] = "Eorzea Arsenal — Gear vs BiS",
        [LocKeys.BisRefresh] = "Mit BiS vergleichen",
        [LocKeys.BisOpen] = "Gear vs BiS",
        [LocKeys.BisLoading] = "Lade BiS-Ziele…",
        [LocKeys.BisReconnect] = "Dein Schlüssel hat keinen Lesezugriff. Bitte neu verbinden, um den BiS-Vergleich zu nutzen.",
        [LocKeys.BisNone] = "Kein BiS-Ziel gefunden. Lege im Webapp eines für deine Gearsets fest.",
        [LocKeys.BisComplete] = "vollständig",
        [LocKeys.BisSummary] = "{0}/{1} Slots passen",
        [LocKeys.BisHave] = "habe {0} → BiS {1}",
        [LocKeys.BisMissing] = "leer → BiS {0}",
        [LocKeys.BisMateriaDiff] = "Materia abweichend",
        [LocKeys.BisTooltipHeader] = "Eorzea Arsenal — BiS",
        [LocKeys.BisTooltipToggle] = "BiS-Info beim Item-Hover anzeigen",
        [LocKeys.BisShowSourcing] = "'Bezug' bei BiS-Teilen anzeigen",
        [LocKeys.BisShowSourcingHint] = "Beim Überfahren eines BiS-Teils zusätzlich zeigen, woher es kommt und was es kostet (Savage / Tome). Liest unpersönliche Spieldaten vom Server.",
        [LocKeys.BisYouHave] = "ausgerüstet: {0}",
        [LocKeys.BisOwned] = "im Besitz (Inventar/Arsenal)",
        [LocKeys.BisNotOwned] = "nicht im Inventar/Arsenal",
        [LocKeys.BisMateriaList] = "Materia: {0}",
        [LocKeys.BisMateriaWrong] = "Falsch: {0}",
        [LocKeys.BisMateriaMissing] = "Fehlt: {0}",
        [LocKeys.BisNoTarget] = "Kein BiS-Ziel für dieses Gearset (#{0}). Im Webapp festlegen.",
        [LocKeys.BisScopeCurrent] = "Aktuelles Set",
        [LocKeys.BisScopeAll] = "Alle Sets",
        [LocKeys.BisFilterLabel] = "Filter",
        [LocKeys.BisFilterAll] = "Alle Slots",
        [LocKeys.BisFilterIncomplete] = "Nur unvollständige",
        [LocKeys.BisFilterMateria] = "Nur Materia-Probleme",
        [LocKeys.BisNothingShown] = "Mit dem aktuellen Filter gibt es nichts anzuzeigen.",
        [LocKeys.BisCopyName] = "Namen kopieren",
        [LocKeys.BisItemHint] = "Linksklick: im Chat verlinken · Rechtsklick: weitere Optionen",
        [LocKeys.DtrClickHint] = "Klick: Status öffnen",
        [LocKeys.ShowDtrBar] = "Eintrag in der Server-Info-Leiste",
        [LocKeys.ShowDtrBarHint] = "Zeigt einen kompakten Status (zuletzt übertragen) in der Server-Info-Leiste im Spiel (oben rechts).",
        [LocKeys.BisShoppingList] = "Einkaufsliste",
        [LocKeys.BisShoppingItems] = "Noch zu holen",
        [LocKeys.BisShoppingMateria] = "Materia zu holen",
        [LocKeys.BisShoppingEmpty] = "Nichts zu holen — du besitzt alles für die angezeigten Sets!",
        [LocKeys.BisGridView] = "Raster",

        [LocKeys.SyncInventory] = "Auch Besitz (Inventar) übertragen",
        [LocKeys.SyncInventoryHint] =
            "Überträgt, welche Ausrüstung du besitzt (angelegt, Arsenal, Taschen, Satteltasche, " +
            "Schrank), damit die Webapp abhaken kann, was du schon hast. Opt-in, wie bei der Ausrüstung.",
        [LocKeys.SyncRetainers] = "Gehilfen einbeziehen",
        [LocKeys.SyncRetainersHint] = "Scannt auch die Ausrüstung eines Gehilfen, wenn du ihn an der Rufglocke öffnest.",
        [LocKeys.InventorySyncButton] = "Inventar synchronisieren",
        [LocKeys.InventorySyncHint] = "Besuche deine Gehilfen, um deren Bestand zu aktualisieren.",
        [LocKeys.InventoryStarted] = "Synchronisiere Inventar…",
        [LocKeys.InventorySuccess] = "{0} Gegenstand/Gegenstände in {1} Bereich(en) synchronisiert.",
        [LocKeys.StatusLastInventory] = "Letzte Inventar-Synchronisierung",
        [LocKeys.Error403Inventory] = "Deinem Schlüssel fehlt die Berechtigung inventory:write. Bitte neu verbinden, um den Inventar-Upload zu nutzen.",

        [LocKeys.SyncWeekly] = "Auch die wöchentliche Checkliste übertragen",
        [LocKeys.SyncWeeklyHint] =
            "Füllt deine wöchentliche Checkliste in der Webapp automatisch aus dem Spiel (Steine diese " +
            "Woche, Sammelaufträge erledigt). Es werden nur sicher auslesbare Werte gesendet, deine " +
            "manuellen Einträge werden nie überschrieben. Opt-in, wie bei der Ausrüstung.",
        [LocKeys.WeeklySyncButton] = "Checkliste synchronisieren",
        [LocKeys.WeeklyStarted] = "Synchronisiere wöchentliche Checkliste…",
        [LocKeys.WeeklySuccess] = "{0} Wochenfeld(er) synchronisiert.",
        [LocKeys.StatusLastWeekly] = "Letzte Checklisten-Synchronisierung",
        [LocKeys.Error403Weekly] = "Deinem Schlüssel fehlt die Berechtigung characters:write. Bitte neu verbinden, um die wöchentliche Checkliste zu nutzen.",

        [LocKeys.SectionActions] = "Aktionen",
        [LocKeys.SectionView] = "Ansehen",
        [LocKeys.SectionManage] = "Verwaltung",
        [LocKeys.StatusConnectHint] = "Nicht verbunden. Öffne die Einstellungen, um dein Eorzea-Arsenal-Konto zu verknüpfen.",
        [LocKeys.TabSync] = "Übertragung",
        [LocKeys.TabDisplay] = "Anzeige",
        [LocKeys.TabCharacters] = "Charaktere",
        [LocKeys.TabConnection] = "Verbindung",

        [LocKeys.LogWindowTitle] = "Eorzea Arsenal — Log",
        [LocKeys.OpenLog] = "Log",
        [LocKeys.LogCopy] = "Kopieren",
        [LocKeys.LogClear] = "Leeren",
        [LocKeys.LogEmpty] = "Noch keine Meldungen.",

        ["slot.weapon"] = "Waffe",
        ["slot.offhand"] = "Nebenhand",
        ["slot.head"] = "Kopf",
        ["slot.body"] = "Rumpf",
        ["slot.hands"] = "Hände",
        ["slot.legs"] = "Beine",
        ["slot.feet"] = "Füße",
        ["slot.ears"] = "Ohren",
        ["slot.neck"] = "Hals",
        ["slot.wrists"] = "Handgelenke",
        ["slot.ringleft"] = "Ring (links)",
        ["slot.ringright"] = "Ring (rechts)",

        ["source.crafted"] = "Handwerk",
        ["source.raid"] = "Raid",
        ["source.tome"] = "Steine",
        ["source.augmented_tome"] = "Tome+",
        ["source.alliance"] = "Allianz-Raid",
        ["source.dungeon"] = "Dungeon",
        ["source.extreme"] = "Extrem",
        ["source.trial"] = "Prüfung",
        ["source.ultimate"] = "Ultimativ",
        ["source.relic"] = "Relikt",
        ["source.pvp"] = "PvP",
        ["source.other"] = "Sonstige",

        [LocKeys.TeamsOpen] = "Teams",
        [LocKeys.SyncTeams] = "Teams-Begleiter",
        [LocKeys.SyncTeamsHint] = "Zeigt Kalender, Mit-Spickzettel, Inhalts-Hub, Farm und FFLogs deiner Teams im Spiel, erlaubt Zu-/Absagen und Abwesenheiten und meldet Loot, Erinnerungen und neue Termine. Benötigt einen Schlüssel mit teams:read / teams:write.",
        [LocKeys.TeamsDisabledHint] = "Der Teams-Begleiter ist aus. Aktiviere ihn in den Einstellungen (benötigt einen Schlüssel mit den teams-Rechten).",
        [LocKeys.TeamsScopeHint] = "Deinem Schlüssel fehlt ein teams-Recht — einmal in den Einstellungen neu verbinden.",
        [LocKeys.TeamsTabCalendar] = "Termine",
        [LocKeys.TeamsTabMit] = "Mit-Plan",
        [LocKeys.TeamsTabContent] = "Inhalte",
        [LocKeys.TeamsTabFarm] = "Farm",
        [LocKeys.TeamsTabLogs] = "FFLogs",
        [LocKeys.TeamsTabAbsence] = "Abwesenheit",
        [LocKeys.TeamsTeamLabel] = "Team",
        [LocKeys.TeamsLoading] = "Lädt…",
        [LocKeys.TeamsNoTeams] = "Keine Teams.",
        [LocKeys.TeamsRefresh] = "Aktualisieren",
        [LocKeys.TeamsHelp] = "Hilfe",
        [LocKeys.TeamsWorking] = "Wird gespeichert…",
        [LocKeys.TeamsSaved] = "Gespeichert.",
        [LocKeys.TeamsNoEvents] = "Keine anstehenden Termine.",
        [LocKeys.TeamsContentsLabel] = "Inhalt",
        [LocKeys.TeamsAttendCounts] = "Ja {0} · Vielleicht {1} · Nein {2} · von {3}",
        [LocKeys.TeamsRsvpYes] = "Ja",
        [LocKeys.TeamsRsvpMaybe] = "Vielleicht",
        [LocKeys.TeamsRsvpNo] = "Nein",
        [LocKeys.TeamsPlanLabel] = "Plan",
        [LocKeys.TeamsJobLabel] = "Job",
        [LocKeys.TeamsAllJobs] = "Alle Jobs",
        [LocKeys.TeamsNoPlan] = "Kein Mit-Plan.",
        [LocKeys.TeamsMechanics] = "Mechaniken",
        [LocKeys.TeamsCooldowns] = "Cooldowns",
        [LocKeys.TeamsNoPlacements] = "Keine Cooldowns für diesen Job.",
        [LocKeys.TeamsBosses] = "Bosse & Drops",
        [LocKeys.TeamsResources] = "Ressourcen",
        [LocKeys.TeamsNoContent] = "Keine Inhalte.",
        [LocKeys.TeamsNoFarm] = "Keine geteilten Gearsets.",
        [LocKeys.TeamsCore] = "Stamm",
        [LocKeys.TeamsSubstitute] = "Ersatz",
        [LocKeys.TeamsTargetNone] = "Kein BiS-Ziel.",
        [LocKeys.TeamsComplete] = "BiS komplett.",
        [LocKeys.TeamsMissing] = "Fehlt noch",
        [LocKeys.TeamsLogsNotConnected] = "FFLogs ist für dieses Team nicht verbunden.",
        [LocKeys.TeamsNoReports] = "Keine aktuellen Berichte.",
        [LocKeys.TeamsKillsWipes] = "{0} Kills · {1} Wipes",
        [LocKeys.TeamsAbsenceFrom] = "Von",
        [LocKeys.TeamsAbsenceTo] = "Bis",
        [LocKeys.TeamsAbsenceNote] = "Notiz",
        [LocKeys.TeamsAbsenceAdd] = "Abwesenheit eintragen",
        [LocKeys.TeamsAbsenceDelete] = "Löschen",
        [LocKeys.TeamsAbsenceInvalid] = "Bitte gültige Daten eingeben.",
        [LocKeys.TeamsNoAbsences] = "Keine Abwesenheiten.",
        [LocKeys.TeamsErrorGeneric] = "Konnte nicht geladen werden. Erneut versuchen.",
        [LocKeys.TeamsErrorForbidden] = "Das darfst du nicht.",
        [LocKeys.TeamsNotMember] = "Du bist kein Mitglied dieses Teams.",
        [LocKeys.TeamsErrorNetwork] = "Netzwerkfehler. Versuche es später erneut.",
        [LocKeys.TeamsCalendarOpen] = "Kalender",
        [LocKeys.TeamsCalendarOpenWeb] = "Im Web öffnen",
        [LocKeys.TeamsCalendarPickDay] = "Wähle einen Tag, um seine Termine zu sehen.",
        [LocKeys.TeamsOpenWeb] = "Im Web öffnen",
        [LocKeys.TeamsPhasesLabel] = "Phasen:",
        [LocKeys.TeamsFilterLabel] = "Mechaniken:",
        [LocKeys.TeamsTagRaidwide] = "Raidwide",
        [LocKeys.TeamsTagTankbuster] = "Tankbuster",
        [LocKeys.TeamsTagOther] = "Sonstige",
        [LocKeys.TeamsColTime] = "Zeit",
        [LocKeys.TeamsColMechanic] = "Mechanik",
        [LocKeys.TeamsRecast] = "Reaktivierung",
        [LocKeys.TeamsDuration] = "Dauer",
        [LocKeys.TeamsResLink] = "Link",
        [LocKeys.TeamsResVideo] = "Video",
        [LocKeys.TeamsResPlan] = "Plan",
        [LocKeys.TeamsResNote] = "Notiz",
        [LocKeys.TeamsResImage] = "Bild",
        [LocKeys.TeamsResPdf] = "PDF",
        [LocKeys.TeamsResFile] = "Datei",
        [LocKeys.TeamsFflogsReport] = "Bericht",
        [LocKeys.TabTeams] = "Teams",
        [LocKeys.TeamsDispIconText] = "Icon + Text",
        [LocKeys.TeamsDispIcon] = "Nur Icon",
        [LocKeys.TeamsDispText] = "Nur Text",
        [LocKeys.TeamsMitDisplayLabel] = "Mit-Cooldowns",
        [LocKeys.TeamsMitDisplayHint] = "Wie Cooldowns im Mit-Zeitstrahl erscheinen. 'Nur Icon' zeigt den Namen beim Überfahren.",
        [LocKeys.TeamsResourceDisplayLabel] = "Ressourcen-Beschriftung",
        [LocKeys.TeamsResourceDisplayHint] = "Wie der Typ einer Inhalts-Ressource (Link/Notiz/Datei…) beschriftet wird.",
        [LocKeys.TeamsShowNotes] = "Notiztext anzeigen",
        [LocKeys.TeamsShowNotesHint] = "Zeigt den vollen Text von Notiz-Ressourcen inline (aus = nur der Titel).",
        [LocKeys.TeamsRange] = "Reichweite",
        [LocKeys.TeamsRadius] = "Radius",
        [LocKeys.TeamsCast] = "Aktivieren",
        [LocKeys.TeamsInstant] = "Sofort",
        [LocKeys.TeamsCalAllPresent] = "alle da",
        [LocKeys.TeamsCalUnclear] = "unklar",
        [LocKeys.TeamsCalMissing] = "jemand fehlt",
        [LocKeys.TeamsRecurring] = "wiederkehrend",
        [LocKeys.TeamsSingle] = "einmalig",
        [LocKeys.TeamsTabEvents] = "Termine",
        [LocKeys.TeamsShowPast] = "Abgelaufene anzeigen ({0})",
        [LocKeys.TeamsDefaultJobLabel] = "Standard-Jobanzeige",
        [LocKeys.TeamsDefaultCurrentJob] = "Aktueller Job",
        [LocKeys.TeamsDefaultAllJobsOpt] = "Alle Jobs",
        [LocKeys.TeamsDefaultShowOther] = "'Sonstige'-Mechaniken standardmäßig zeigen",
        [LocKeys.TeamsDefaultShowOtherHint] = "An: der Mit-Zeitstrahl zeigt auch ungetaggte/sonstige Mechaniken; aus: nur Raidwides und Tankbuster.",
        [LocKeys.TeamsDefaultPhasesLabel] = "Standard-Phasen",
        [LocKeys.TeamsDefaultPhasesAll] = "Alle Phasen",
        [LocKeys.TeamsDefaultPhasesFirst] = "Nur erste Phase",
        [LocKeys.TeamsDefaultPhasesHint] = "Welche Phasen beim Öffnen eines Mit-Plans angehakt sind. Pro Plan bleibt es weiter umschaltbar.",
        [LocKeys.TeamsEventScale] = "Textgröße Termine",
        [LocKeys.TeamsEventScaleHint] = "Skaliert die Schrift im Termine-Tab, damit lange Listen lesbar bleiben.",
        [LocKeys.TeamsFarmColSlot] = "Slot",
        [LocKeys.TeamsFarmColSource] = "Quelle",
        [LocKeys.TeamsFarmColHow] = "Bezug",
        [LocKeys.TeamsFarmUnknownSource] = "unbekannt",
        [LocKeys.TeamsFarmRetired] = "nicht mehr erhältlich",
        [LocKeys.TeamsFarmMarket] = "Marktbrett",
        [LocKeys.TeamsFarmCraft] = "Handwerk",
        [LocKeys.TeamsFarmCoffer] = "Koffer",
        [LocKeys.TeamsFarmWaysHeading] = "Bezugswege",
        [LocKeys.TeamsFarmHandIn] = "abgeben",
        [LocKeys.TeamsFarmShowOnMap] = "NPC auf Karte anzeigen",
        [LocKeys.SourceStepFight] = "Erspielen",
        [LocKeys.SourceStepBuy] = "Kaufen",
        [LocKeys.SourceStepAugment] = "Aufwerten",
        [LocKeys.SourceStepCraft] = "Herstellen",
        [LocKeys.SourceStepBase] = "Basis-Teil besorgen",
        [LocKeys.SourceNoInfo] = "Noch keine Bezugsinfos",
        [LocKeys.SourceHave] = "du hast genug",
        [LocKeys.SourceBaseOwned] = "Basis vorhanden",
        [LocKeys.SourceOr] = "oder",
        [LocKeys.WhatsNewOpen] = "Was ist neu",
        [LocKeys.WhatsNewIntro] = "Die wichtigsten Änderungen jeder Version, kurz gefasst. Das vollständige technische Changelog liegt auf GitHub.",
        [LocKeys.WhatsNewInstalled] = "installiert",
        [LocKeys.WhatsNewKindAdded] = "Neu",
        [LocKeys.WhatsNewKindImproved] = "Verbessert",
        [LocKeys.WhatsNewKindFixed] = "Behoben",
        [LocKeys.WhatsNewFullChangelog] = "Vollständiges Changelog",
        [LocKeys.WhatsNewOnUpdate] = "'Was ist neu' nach einem Update anzeigen",
        [LocKeys.WhatsNewOnUpdateHint] = "Öffnet diese Liste einmalig nach einem Plugin-Update. Aus: der Menüeintrag wird stattdessen hervorgehoben.",
        [LocKeys.TeamsAbsenceNew] = "Neue Abwesenheit",
        [LocKeys.TeamsAbsenceEditing] = "Abwesenheit bearbeiten",
        [LocKeys.TeamsAbsenceUpdate] = "Änderungen speichern",
        [LocKeys.TeamsAbsenceCancel] = "Abbrechen",
        [LocKeys.TeamsAbsenceCurrent] = "Deine Abwesenheiten",
        [LocKeys.TeamsAbsenceEdit] = "Bearbeiten",
        [LocKeys.TeamsAbsenceRangeInvalid] = "Das Enddatum liegt vor dem Startdatum.",

        [LocKeys.AdvisorOpen] = "Kaufberater",
        [LocKeys.AdvisorWindowTitle] = "Eorzea Arsenal — Kaufberater",
        [LocKeys.AdvisorIntro] = "Die Ausrüstung auf dem Weg zum BiS: was als Nächstes zu kaufen ist und was du dafür schon auf Lager hast.",
        [LocKeys.AdvisorSetLabel] = "Set",
        [LocKeys.AdvisorPlanHeading] = "Dein gespeicherter Plan",
        [LocKeys.AdvisorNoTarget] = "Für dieses Set liefert der Server noch keine Web-Kennung, deshalb lässt sich kein Plan dazu nachschlagen. Es erscheint hier, sobald der Server das Ziel-Set zu den BiS-Daten mitschickt.",
        [LocKeys.AdvisorNoPlan] = "Für dieses Set ist kein eigenes Layout gespeichert — es gilt die Empfehlung. Du kannst hier auswählen oder es im Kaufberater der Webapp anlegen.",
        [LocKeys.AdvisorNoCharacter] = "Dieser Charakter ist auf dem Server noch nicht verknüpft. Übertrage einmal deine Ausrüstung, dann kann der Kaufberater gelesen werden.",
        [LocKeys.AdvisorPlanSaved] = "gespeichert: {0}",
        [LocKeys.AdvisorPlanWorn] = "getragen",
        [LocKeys.AdvisorPlanOwned] = "vorhanden",
        [LocKeys.AdvisorPlanMissing] = "fehlt noch",
        [LocKeys.AdvisorPlanSummary] = "{0}/{1} Teile erledigt",
        [LocKeys.AdvisorViewRecommendation] = "Empfehlung",
        [LocKeys.AdvisorViewPlan] = "Mein Layout",
        [LocKeys.AdvisorSortLabel] = "Reihenfolge",
        [LocKeys.AdvisorSortPower] = "Größter Zugewinn",
        [LocKeys.AdvisorSortValue] = "Bestes Verhältnis",
        [LocKeys.AdvisorSortCheap] = "Günstigstes zuerst",
        [LocKeys.AdvisorRefresh] = "Neu berechnen",
        [LocKeys.AdvisorBalance] = "{0} Steine · Wochenlimit {1}",
        [LocKeys.AdvisorStepBuy] = "Kaufen",
        [LocKeys.AdvisorStepAugment] = "Aufwerten",
        [LocKeys.AdvisorStepTrial] = "Erspielen (Extrem)",
        [LocKeys.AdvisorStepBooks] = "Bücher eintauschen",
        [LocKeys.AdvisorStepEquip] = "Anlegen",
        [LocKeys.AdvisorWhenNow] = "jetzt",
        [LocKeys.AdvisorWhenWeeks] = "in {0} Woche(n)",
        [LocKeys.AdvisorWhenBooks] = "{0} Buch/Bücher fehlen",
        [LocKeys.AdvisorCostTomes] = "{0} Steine",
        [LocKeys.AdvisorVendor] = "bei {0}",
        [LocKeys.AdvisorLeadsTo] = "auf dem Weg zu {0}",
        [LocKeys.AdvisorNothingToDo] = "Nichts mehr zu tun — das Set sitzt.",
        [LocKeys.AdvisorNoSteps] = "Kein planbarer Schritt: Die {0} offenen Slot(s) lassen sich nicht kaufen (Ultimate, Relikt, Handwerk) — da entscheidet der Drop.",
        [LocKeys.AdvisorNeeds] = "Noch nötig",
        [LocKeys.AdvisorSave] = "Layout speichern",
        [LocKeys.AdvisorAdopt] = "Empfehlung übernehmen",
        [LocKeys.AdvisorDeletePlan] = "Layout löschen",
        [LocKeys.AdvisorSaved] = "Gespeichert.",
        [LocKeys.AdvisorSaveFailed] = "Konnte nicht gespeichert werden — dem Schlüssel fehlt vielleicht das Plan-Recht.",
        [LocKeys.AdvisorIsRecommended] = "empfohlen",
        [LocKeys.AdvisorIsBis] = "BiS",
        [LocKeys.AdvisorLoadingOptions] = "Berechne…",
        [LocKeys.AdvisorUnsaved] = "ungespeicherte Änderungen",
        [LocKeys.TeamsNeedsRequires] = "das Set braucht",
        [LocKeys.TeamsStockUnknown] = "sein Bestand ist für das Plugin nicht sichtbar",
        [LocKeys.BisNeedsHeading] = "Noch nötig für dieses Set",
        [LocKeys.BisNeedsTomes] = "Steine: {0} · du hast {1}",
        [LocKeys.BisNeedsShort] = "{0} fehlen",
        [LocKeys.BisNeedsWeeks] = "≈ {0} Woche(n)",
        [LocKeys.BisNeedsCovered] = "reicht",
        [LocKeys.BisNeedsNothing] = "Für dieses Set ist nichts mehr zu holen.",
        [LocKeys.BisNeedsUnknown] = "Noch {0} Slot(s) offen, aber zu deren Kosten ist nichts bekannt: Sie sind nicht käuflich (Ultimate, Relikt, Handwerk) oder es ist noch kein Kauf dafür hinterlegt.",
        [LocKeys.AdvisorScale] = "Textgröße Kaufberater",
        [LocKeys.AdvisorScaleHint] = "Skaliert das Kaufberater-Fenster. Gegenstandsnamen sind lang und die Auswahllisten haben Dutzende Einträge, deshalb startet es etwas größer.",
        [LocKeys.AdvisorNextBest] = "Jetzt am besten",
        [LocKeys.AdvisorProgress] = "Fortschritt",
        [LocKeys.AdvisorOnBis] = "Auf BiS",
        [LocKeys.AdvisorAvgIlvl] = "ø iLvl",
        [LocKeys.AdvisorYourSet] = "Dein Set",
        [LocKeys.AdvisorOrderHeading] = "Reihenfolge — was zuerst",
        [LocKeys.AdvisorLegend] = "Grün = auf BiS · Blau = besitzt du schon · Orange = nächster Kauf · Grau = schon bestmöglich",
        [LocKeys.AdvisorSlotCapped] = "schon bestmöglich",
        [LocKeys.HoldingWhere] = "Wo es liegt",
        [LocKeys.HoldingBags] = "Inventar",
        [LocKeys.HoldingSaddlebag] = "Satteltasche",
        [LocKeys.HoldingArmoury] = "Arsenal",
        [LocKeys.HoldingEquipped] = "angelegt",
        [LocKeys.HoldingGlamour] = "Kleiderschrank",
        [LocKeys.HoldingArmoire] = "Schrank",
        [LocKeys.HoldingRetainer] = "Gehilfe",
        [LocKeys.HoldingManual] = "auf der Webseite eingetragen",
        [LocKeys.AdvisorStockHeading] = "Deine Vorräte",
        [LocKeys.AdvisorStockHint] = "Serverseitig gezählt, also inklusive Gehilfen — Stand ihres letzten Besuchs.",
        [LocKeys.AdvisorStockEmpty] = "Noch keine Vorratsliste vom Server.",
        [LocKeys.AdvisorStockMaterial] = "Aufwertungsmaterial",
        [LocKeys.AdvisorStockStone] = "Aufwertungsstein",
        [LocKeys.AdvisorStockBook] = "Bücher & Marken",
        [LocKeys.AdvisorLoading] = "Lade Plan…",
        [LocKeys.AdvisorScopeHint] = "Dein Schlüssel hat keinen Zugriff auf Pläne — einmal in den Einstellungen neu verbinden.",
    };

    private static readonly IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Languages =
        new Dictionary<string, IReadOnlyDictionary<string, string>>(StringComparer.Ordinal)
        {
            [English] = En,
            [German] = De,
        };

    private string _language = English;

    /// <summary>Creates a localizer in the given language (defaults to English if unknown).</summary>
    /// <param name="language">Initial two-letter language code.</param>
    public Localizer(string language = English) => Language = language;

    /// <inheritdoc />
    public string Language
    {
        get => _language;
        set => _language = Languages.ContainsKey(value) ? value : English;
    }

    /// <inheritdoc />
    public string Get(string key)
    {
        var table = Languages[_language];
        if (table.TryGetValue(key, out var value))
        {
            return value;
        }

        // Fall back to English, then to the key itself so gaps are visible.
        return Languages[English].TryGetValue(key, out var en) ? en : key;
    }

    /// <inheritdoc />
    public string Get(string key, params object[] args) =>
        string.Format(CultureInfo.CurrentCulture, Get(key), args);
}
